[project]
name = "password-strength"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
python = ">=3.12"
package-mode = false
dependencies = [
    "streamlit",
    "pandas"
]
